language: node_js
cache: npm
notifications:
  email: false
node_js:
  - '11'
  - '10'
install:
  - yarn install
script:
  - yarn lint
  - yarn test
  - yarn test:coverage
after_success:
  - yarn report-coverage
branches:
  only: 
    - master
    - development